const eventDate=new Date("2026-10-25T19:00:00");
const opening=document.getElementById("opening"),site=document.getElementById("site"),openInvitation=document.getElementById("openInvitation");
openInvitation.addEventListener("click",()=>{opening.classList.add("hide");site.classList.add("show");document.body.classList.remove("locked");createPetals(20)});
const ids={days:document.getElementById("days"),hours:document.getElementById("hours"),minutes:document.getElementById("minutes"),seconds:document.getElementById("seconds")};
function updateCountdown(){const d=eventDate-new Date();if(d<=0){Object.values(ids).forEach(e=>e.textContent="00");return}ids.days.textContent=String(Math.floor(d/86400000)).padStart(2,"0");ids.hours.textContent=String(Math.floor(d/3600000)%24).padStart(2,"0");ids.minutes.textContent=String(Math.floor(d/60000)%60).padStart(2,"0");ids.seconds.textContent=String(Math.floor(d/1000)%60).padStart(2,"0")};updateCountdown();setInterval(updateCountdown,1000);
const menuBtn=document.querySelector(".menu-btn"),navLinks=document.querySelector(".nav-links");menuBtn.addEventListener("click",()=>navLinks.classList.toggle("open"));navLinks.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>navLinks.classList.remove("open")));
const musicBtn=document.getElementById("musicBtn"),bgMusic=document.getElementById("bgMusic");musicBtn.addEventListener("click",async()=>{try{if(bgMusic.paused){await bgMusic.play();musicBtn.textContent="♫ Pausar";musicBtn.classList.add("active")}else{bgMusic.pause();musicBtn.textContent="♫ Música";musicBtn.classList.remove("active")}}catch{alert("Agrega tu archivo assets/musica.mp3 para usar la música.")}});
const fireflies=document.querySelector(".fireflies");for(let i=0;i<34;i++){const x=document.createElement("span");x.className="firefly";x.style.left=Math.random()*100+"%";x.style.top=Math.random()*100+"%";x.style.animationDelay=Math.random()*4+"s";x.style.animationDuration=3+Math.random()*4+"s";fireflies.appendChild(x)}
function createPetals(n=8){const c=document.querySelector(".petals");for(let i=0;i<n;i++){const p=document.createElement("span");p.className="petal";p.style.left=Math.random()*100+"%";p.style.setProperty("--drift",Math.random()*220-110+"px");p.style.animationDuration=5+Math.random()*5+"s";p.style.animationDelay=Math.random()*3+"s";c.appendChild(p);setTimeout(()=>p.remove(),11000)}}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.15});document.querySelectorAll(".reveal").forEach(e=>observer.observe(e));
const lightbox=document.getElementById("lightbox"),lightboxImage=document.getElementById("lightboxImage"),closeLightbox=document.getElementById("closeLightbox");document.querySelector(".photo-1").addEventListener("click",()=>{lightboxImage.src="assets/referencia-princesa.png";lightbox.classList.add("show")});function closePhoto(){lightbox.classList.remove("show");lightboxImage.src=""}closeLightbox.addEventListener("click",closePhoto);lightbox.addEventListener("click",e=>{if(e.target===lightbox)closePhoto()});
const shareBtn=document.getElementById("shareBtn");shareBtn.addEventListener("click",async()=>{const data={title:"Mis Quince · Andrea",text:"Estás invitado/a a celebrar conmigo mis 15 años. ✦",url:location.href};if(navigator.share){try{await navigator.share(data)}catch{}}else{try{await navigator.clipboard.writeText(location.href);shareBtn.textContent="¡Enlace copiado!";setTimeout(()=>shareBtn.textContent="Compartir invitación",2200)}catch{alert("Copia la dirección de esta página para compartirla.")}}});
